# Generated by Django 6.0.3 on 2026-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productimages_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku_code',
            field=models.CharField(default='TESTING', help_text='Unique identifier/code for the product (SKU)', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='storage_size',
            field=models.CharField(blank=True, help_text='e.g., 128GB, 256GB', max_length=20, null=True),
        ),
    ]
