# Generated by Django 6.0.3 on 2026-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_currency_productvariant_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('CAD', 'CAD - Canadian Dollar'), ('JPY', 'JPY - Japanese Yen'), ('NGN', 'NGN - Nigerian Naira'), ('GHS', 'GHS - Ghanaian Cedi'), ('KES', 'KES - Kenyan Shilling'), ('ZAR', 'ZAR - South African Rand'), ('TZS', 'TZS - Tanzanian Shilling'), ('UGX', 'UGX - Ugandan Shilling'), ('RWF', 'RWF - Rwandan Franc'), ('XAF', 'XAF - Central African CFA Franc'), ('XOF', 'XOF - West African CFA Franc')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('CAD', 'CAD - Canadian Dollar'), ('JPY', 'JPY - Japanese Yen'), ('NGN', 'NGN - Nigerian Naira'), ('GHS', 'GHS - Ghanaian Cedi'), ('KES', 'KES - Kenyan Shilling'), ('ZAR', 'ZAR - South African Rand'), ('TZS', 'TZS - Tanzanian Shilling'), ('UGX', 'UGX - Ugandan Shilling'), ('RWF', 'RWF - Rwandan Franc'), ('XAF', 'XAF - Central African CFA Franc'), ('XOF', 'XOF - West African CFA Franc')], default='USD', max_length=3),
        ),
    ]
