# Generated by Django 6.0.3 on 2026-03-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='storage_size',
            field=models.CharField(blank=True, default='', help_text='e.g., 128GB, 256GB', max_length=20),
            preserve_default=False,
        ),
    ]
