# Generated by Django 6.0.3 on 2026-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku_code',
            field=models.CharField(blank=True, help_text='Unique identifier/code for the product (SKU)', max_length=40, unique=True),
        ),
    ]
