services:
  web:
    image: sellaris:latest
    volumes:
      - .:/app              # Changed from .. to .
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env.local                # Changed from ../.env.local to .env.local
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - app-network

  db:
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network

  celery_default:
    image: sellaris:latest
    command: celery -A config worker -Q default -l info
    volumes:
      - .:/app              # Changed from .. to .
    env_file:
      - .env.local                # Changed from ../.env.local to .env.local
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  celery_emails:
    image: sellaris:latest
    command: celery -A config worker -Q emails -l info
    volumes:
      - .:/app              # Changed from .. to .
    env_file:
      - .env.local                # Changed from ../.env.local to .env.local
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  celery_beat:
    image: sellaris:latest
    command: celery -A config beat -l info
    volumes:
      - .:/app              # Changed from .. to .
    env_file:
      - .env.local                # Changed from ../.env.local to .env.local
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  
networks:
  app-network:
    driver: bridge
