# Generated by Django 6.0.3 on 2026-03-26 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_wishlist_name_per_user',
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('name', 'user', 'session_id'), name='unique_wishlist_name_per_owner'),
        ),
    ]
