# Generated by Django 6.0.3 on 2026-04-01 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['created_at'], name='wishlists_w_created_28811c_idx'),
        ),
    ]
