# Generated by Django 6.0.3 on 2026-04-01 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'updated_at'], name='cart_cart_user_id_519ac1_idx'),
        ),
    ]
