# Generated by Django 6.0.3 on 2026-04-04 15:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price must be non-negative', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='initialized', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('payment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('reference_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'initialized')), fields=('order',), name='unique_initialized_payment_per_order')],
            },
        ),
    ]
