# Generated by Django 6.0.3 on 2026-04-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_currency_alter_productvariant_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SET', 'Set Stock'), ('INCREASE', 'Increase Stock'), ('DECREASE', 'Decrease Stock'), ('RESERVE', 'Reserve Stock'), ('RELEASE', 'Release Stock'), ('CONFIRM', 'Confirm Deduction')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['product_variant'], name='inventory_i_product_b97b62_idx'), models.Index(fields=['created_at'], name='inventory_i_created_108a29_idx')],
            },
        ),
    ]
