from django.db import models
from uuid import uuid4
from apps.orders.models import Order
from core.utils import get_price_decimal_field
import secrets

def generate_reference():
    return f"flw_{secrets.token_hex(12)}"

class PaymentStatus(models.TextChoices):
    INITIALIZED = "initialized", "Initialized"
    PENDING = "pending", "Pending"
    SUCCESS = "success", "Success"
    FAILED = "failed", "Failed"


class Payment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="payments"
    )

    amount = get_price_decimal_field() # snapshot of the order price
    currency = models.CharField(max_length=10, default="NGN")

    status = models.CharField(
        max_length=20,
        choices=PaymentStatus.choices,
        default=PaymentStatus.INITIALIZED
    )

    # Flutterwave, Paystack etc.
    provider = models.CharField(max_length=50)
    payment_link = models.URLField(max_length=1000, blank=True, null=True)

    # Generated by this system
    reference_id = models.CharField(
        max_length=255, 
        unique=True,
        default=generate_reference,
        editable=False
    ) 

    # Generated by the provider
    transaction_id = models.CharField(
        max_length=255, 
        null=True, 
        blank=True,
        editable=False
        # We didn't set unique=True, because some providers may not send the
        # transaction_id immediately or could reuse patterns accross enviroments
    ) 

    created_at = models.DateTimeField(auto_now_add=True)
    confirmed_at = models.DateTimeField(null=True, blank=True)


class PaymentWebhookLog(models.Model):
    provider = models.CharField(max_length=50)
    payload = models.JSONField()
    headers = models.JSONField()
    status = models.CharField(max_length=20, blank=True, null=True)
    detail = models.CharField(max_length=200, blank=True)
    processed = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)