from django.db import models
from uuid import uuid4
from apps.orders.models import Order
from core.utils import get_price_decimal_field
import secrets

def generate_reference(provider: str):
    if not provider:
        raise ValueError("Provider must be set before generating reference_id")
    prefix_map = {
        "flutterwave": "flw",
        "paystack": "pst",
    }
    prefix = prefix_map.get(provider.lower(), "gen")
    return f"{prefix}_{secrets.token_hex(12)}"

class PaymentStatus(models.TextChoices):
    INITIALIZED = "initialized", "Initialized"
    PENDING = "pending", "Pending"
    SUCCESS = "success", "Success"
    FAILED = "failed", "Failed"


class Payment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="payments"
    )

    amount = get_price_decimal_field() # snapshot of the order price
    currency = models.CharField(max_length=10, default="NGN")

    status = models.CharField(
        max_length=20,
        choices=PaymentStatus.choices,
        default=PaymentStatus.INITIALIZED
    )

    # Flutterwave, Paystack etc.
    provider = models.CharField(max_length=50)
    payment_link = models.URLField(max_length=1000, blank=True, null=True)

    # Generated by this system
    reference_id = models.CharField(
        max_length=255, 
        unique=True,
        editable=False
    ) 

    # Generated by the provider
    transaction_id = models.CharField(
        max_length=255, 
        null=True, 
        blank=True,
        editable=False
        # We didn't set unique=True, because some providers may not send the
        # transaction_id immediately or could reuse patterns accross enviroments
    ) 

    created_at = models.DateTimeField(auto_now_add=True)
    confirmed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["order"],
                condition=models.Q(status="initialized"),
                name="unique_initialized_payment_per_order"
            )
        ]
    
    def save(self, *args, **kwargs):
        if not self.reference_id:
            self.reference_id = generate_reference(self.provider)
        super().save(*args, **kwargs)


class PaymentWebhookLog(models.Model):
    provider = models.CharField(max_length=50)
    payload = models.JSONField()
    headers = models.JSONField()
    status = models.CharField(max_length=20, blank=True, null=True)
    detail = models.CharField(max_length=200, blank=True)
    processed = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)