"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import environ
import cloudinary
from pathlib import Path
from celery.schedules import crontab

env = environ.Env()

# To this (goes up from settings/ to config/ to project root):
# So, we can Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent 

# Read .env file if it exists
# Since Docker handles env variables, we make reading env optional
# so it doesn't crash if it is missing (common in some CI/CD pipelines).
if (BASE_DIR / '.env').exists():
    environ.Env.read_env(BASE_DIR / '.env')


# The Application Secret Key
SECRET_KEY = env('SECRET_KEY')

PAYMENT_REDIRECT_PATH = env('PAYMENT_REDIRECT_PATH')

# Flutterwave Payment Integration Credentials
FLW_SECRET_KEY = env("FLW_SECRET_KEY")
FLW_SECRET_HASH = env("FLW_SECRET_HASH")
FLW_BASE_URL = env("FLW_BASE_URL")

# PAYSTACK Payment Integration Credentials
PST_SECRET_KEY = env("PST_SECRET_KEY")

ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost'
]

FRONTEND_ORIGIN = env("FRONTEND_ORIGIN", default='')

# Email Config
EMAIL_PROVIDER = env("EMAIL_PROVIDER", default="smtp")

EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

VERIFY_EMAIL_PATH = env("VERIFY_EMAIL_PATH", default='/verify-email')

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

EMAIL_FROM_NAME = "MyShop"

SENDPULSE_CLIENT_ID = env("SENDPULSE_CLIENT_ID")
SENDPULSE_CLIENT_SECRET = env("SENDPULSE_CLIENT_SECRET")

# OAuth Provders Credentials
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
FACEBOOK_APP_ID = env("FACEBOOK_APP_ID")
FACEBOOK_APP_SECRET = env("FACEBOOK_APP_SECRET")
APPLE_CLIENT_ID = env("APPLE_CLIENT_ID")

# Token config
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24  # 24 hours

# CSRF / CORs config
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CSRF_COOKIE_HTTPONLY = False  # Allows JS to read the cookie
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    # my apps
    'apps.cart',
    'apps.inventory',
    'apps.notifications',
    'apps.orders',
    'apps.payments',
    'apps.products',
    'apps.users',
    'apps.wishlists',

    # 3rd party apps
    'rest_framework',
    'storages',
    'django_celery_beat',
    'corsheaders',
    'django_filters',

    # default django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # cors, leave this on top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_SAVE_EVERY_REQUEST = True       # refresh expiry on activity

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Use the Postgres link from environment variables
DATABASES = {
    'default': env.db('DATABASE_URL')
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


# Determines the total max size of a request body before a SuspiciousOperation
# error is raised

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760 # 10 MB


# This defines the maximum size of a single file that will be stored in memory.
# Anything larger is streamed to a temporary file (/tmp).

FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880 # 5 MB


# Reduce the total number of files in a single request, to prevent or reduce the 
# impact of DoS attacks

DATA_UPLOAD_MAX_FILES = 20 


# Celery config
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TASK_TRACK_STARTED = False  # Disable tracking task start
CELERY_IGNORE_RESULT = True  # Don't track task results (webhook tasks don't need them)


# Celery beat schedule

CELERY_BEAT_SCHEDULE = {
    "cleanup-guest-data": {
        "task": "tasks.cleanup_data.cleanup_expired_guest_data",
        "schedule": crontab(hour=3, minute=0),  # daily 3AM
    },
    "release-expired-stock-reservations": {
        "task": "tasks.cleanup_data.release_expired_reservations",
        "schedule": 300.0,  # every 5 mins
    },
}


# DRF Config

REST_FRAMEWORK = {
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1",],
    "DEFAULT_THROTTLE_RATES": {
        "flutterwave_webhook": "60/min",
        "paystack_webhook":"60/min",
        "login": "5/min",
        "register": "3/min",
        "verify_email": "10/min",
        "resend_verification": "2/min",
        "oauth": "10/min",
    },
    "DEFAULT_PAGINATION_CLASS": "core.pagination.CustomPagination",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

APPEND_SLASH = True # Append trailing slash

# Logging config

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },

    "loggers": {
        "payments": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CURRENCY_CHOICES = [
    # Major International Currencies (Supported by Flutterwave/Stripe)
    ('USD', 'USD - US Dollar'),
    ('EUR', 'EUR - Euro'),
    ('GBP', 'GBP - British Pound'),
    ('CAD', 'CAD - Canadian Dollar'),
    ('JPY', 'JPY - Japanese Yen'),
    
    # Major African Currencies (Supported by Flutterwave/Paystack)
    ('NGN', 'NGN - Nigerian Naira'),
    ('GHS', 'GHS - Ghanaian Cedi'),
    ('KES', 'KES - Kenyan Shilling'),
    ('ZAR', 'ZAR - South African Rand'),
    ('TZS', 'TZS - Tanzanian Shilling'),
    ('UGX', 'UGX - Ugandan Shilling'),
    ('RWF', 'RWF - Rwandan Franc'),
    ('XAF', 'XAF - Central African CFA Franc'),
    ('XOF', 'XOF - West African CFA Franc'),
]

# Change this to your preferred choice of currency
DEFAULT_CURRENCY_CHOICE = "NGN"